int process_checkout(int argc,char ** argv);
int process_update(int argc,char ** argv);
int process_upgrade(int sockfd, int argc,char ** argv);
int process_commit(int sockfd, int argc,char ** argv);
int process_push(int sockfd, int argc,char ** argv);
int process_create(int argc,char ** argv);
int process_destroy(int argc,char ** argv);
int process_add(int argc,char ** argv);
int process_remove(int sockfd, int argc, char **argv);
int process_currentversion(int sockfd, int argc,char ** argv);
int process_history(int argc,char ** argv);
int process_rollback(int argc,char ** argv);
